---
- hosts: all
  become: yes
  tasks:
  - name: update packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
  - name: Install packages
    apt:
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      state: latest
      cache_valid_time: 3600
  - name: Add Docker GPG apt Key
    apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
  - name: Add Docker Repository
    apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
  - name: Update apt and install docker-ce
    apt:
      name: 
        - docker-ce
        - docker-compose
  - name: Install Docker Module for Python
    pip:
      name: docker


