version: "3.3"

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    env_file:
        "./.env"
    ports:
      - ${DB_PORT}:3306
    networks:
      - app-network
    expose:
      - ${DB_PORT}
    command: --innodb_use_native_aio=0 --socket=/tmp/mysql.sock --bind_address=0.0.0.0
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  wordpress:
    depends_on:
      - db
    container_name: wordpress
    image: wordpress:latest
    volumes:
      - ./wordpress_data:/var/www/html
    ports:
      - ${WORDPRESS_PORT}:80
    restart: always
    networks:
      - app-network
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_DATABASE}

networks:
  app-network:
    driver: 'bridge'